A few minor changes
EndeavourOS-Community-Editions/bspwm pull request #38
Opened 2023-05-20 00:33 UTC by HabGesehen

Changes made to:
     - Sxhkdrc
     - polybar config.ini
     - readme.md

2023-05-21 04:02 UTC, flyingcakes85 requested changes
Thanks for this PR. There's minor change I've requested in the README.

Currently not merging your PR, since the screenshot is doesn't show icon fonts properly. I'll have to look into why they're broken. Will merge your PR once we have a new screenshot with icons showing up.

2023-05-21 04:02 UTC, flyingcakes85 commented on README.md
> +<br>
We don't need html tag here. An empty line is sufficient.

2023-05-21 04:02 UTC, flyingcakes85 commented on bspwm.png
This is something I will have to look into. Icon fonts seem to be broken.

2023-05-21 18:41 UTC, HabGesehen commented on README.md
> +<br>
Ok. Will change. I will try to find a new image if you need.

2023-05-22 18:58 UTC, flyingcakes85 commented on bspwm.png
![image](https://github.com/EndeavourOS-Community-Editions/bspwm/assets/48585950/84dd7d8e-88a1-4b6c-a2c4-e13fcbe36cb4)

@HabGesehen Please see this screenshot. This is a fresh install of EndeavourOS, where icons on Polybar are correctly rendered. I suspect your configuration has an error.

2023-12-08 11:39 UTC, closed without merging